general.live_config_reload = true

[env]
TERM = "alacritty"

#[shell]
#program = "/bin/zsh"
#args = ["-l"]

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window]
opacity = 1.0
dynamic_padding = true
decorations_theme_variant = "Light"
[window.padding]
# decoration = "none"
x = 10
y = 12

[font]
  normal = {family = "Hack Nerd Font Mono", style = "Regular"}
  bold = {family = "Hack Nerd Font Mono", style = "Bold"}
  italic = {family = "Hack Nerd Font", style = "Italic"}
  bold_italic = {family = "Hack Nerd Font", style = "Bold Italic"}
  size = 11


[cursor]
style = {shape =  "Block", blinking = "Never"}
unfocused_hollow = true

# BEGIN WAL
[colors.primary]
background = '#12283d'
foreground = '#dadbde'

[colors.cursor]
text   = '#12283d' # Apply background color to color of text inside cursor
cursor = '#dadbde' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#12283d' # Same as above
cursor  = '#dadbde'

[colors.search.matches]
foreground = '#12283d' # Same as above
background = '#dadbde' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#98999b'
background = '#dadbde'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#12283d'
red     = '#729FC6'
green   = '#C19FB7'
yellow  = '#C5B1BB'
blue    = '#97B2CD'
magenta = '#B2B8CA'
cyan    = '#C5BBC2'
white   = '#dadbde'

[colors.bright]
black   = '#98999b'
red     = '#729FC6'
green   = '#C19FB7'
yellow  = '#C5B1BB'
blue    = '#97B2CD'
magenta = '#B2B8CA'
cyan    = '#C5BBC2'
white   = '#dadbde'
# END WAL
